//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAuth {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinAuth.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请在输入验证码后再次登录。.
        /// </summary>
        internal static string CaptchaNeeded {
            get {
                return ResourceManager.GetString("CaptchaNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请查看账号绑定邮箱，输入邮件验证码后继续。.
        /// </summary>
        internal static string EmailAuthNeeded {
            get {
                return ResourceManager.GetString("EmailAuthNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的帐户似乎已添加了身份验证器，需要移除现有的身份验证器才可以通过账号导入.
        /// </summary>
        internal static string error_HasAuthenticator {
            get {
                return ResourceManager.GetString("error_HasAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的激活码.
        /// </summary>
        internal static string error_invalid_activation_code {
            get {
                return ResourceManager.GetString("error_invalid_activation_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 来自 Steam 的无效响应：{0}.
        /// </summary>
        internal static string error_invalid_response_from_steam_ {
            get {
                return ResourceManager.GetString("error_invalid_response_from_steam_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法发送短信，检查您的手机号已在您的 Steam 帐户中注册。.
        /// </summary>
        internal static string error_ITwoFactorService_AddAuthenticator_v0001 {
            get {
                return ResourceManager.GetString("error_ITwoFactorService_AddAuthenticator_v0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 来自Steam的无效响应（没有OAuth令牌）。.
        /// </summary>
        internal static string error_NoOAuth {
            get {
                return ResourceManager.GetString("error_NoOAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 激活时出现了问题。Steam 服务器可能存在问题。请稍后再试。.
        /// </summary>
        internal static string error_on_activating {
            get {
                return ResourceManager.GetString("error_on_activating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您所输入的账户名或密码不正确。.
        /// </summary>
        internal static string error_password {
            get {
                return ResourceManager.GetString("error_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的 Steam 帐户必须附有支持短信的手机号码, {0}请到 Steam 客户端或 Steam 网站的帐户详细信息添加电话号码。.
        /// </summary>
        internal static string error_steamguard_phoneajax_ {
            get {
                return ResourceManager.GetString("error_steamguard_phoneajax_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP登录请求过于频繁，请稍后重试。.
        /// </summary>
        internal static string error_TooManyRequests {
            get {
                return ResourceManager.GetString("error_TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请查看账号绑定手机号信息，输入验证码后继续。.
        /// </summary>
        internal static string RequiresActivation {
            get {
                return ResourceManager.GetString("RequiresActivation", resourceCulture);
            }
        }
    }
}
